# Main configuration for the data generation pipeline
dataset_settings:
  n_samples: 1000
  n_initial_features: 5
  random_state: 42

feature_generation:
  feature_parameters:
    feature_0: {mean: 10, std: 1}
    feature_1: {mean: -5, std: 0.5}
    feature_2: {mean: 0, std: 2}
    feature_3: {mean: 3, std: 1.5}
    feature_4: {mean: -2, std: 0.8}
  feature_types:
    feature_0: "discrete"
    feature_1: "continuous"
    feature_2: "continuous"
    feature_3: "discrete"
    feature_4: "continuous"

perturbation:
  perturbation_type: "gaussian"
  features: ["feature_0", "feature_1"] 
  scale: 0.15

add_features:
  n_new_features: 2
  feature_parameters:
    feature_5: {mean: 5, std: 1.2}
    feature_6: {mean: -3, std: 0.9}
  feature_types:
    feature_5: "continuous"
    feature_6: "discrete"

create_target:
  features_to_use: ["feature_0", "feature_1", "feature_2"]
  weights: [0.5, -0.3, 1.2]
  noise_level: 0.05
  function_type: "polynomial"

visualisation:
  features: ["feature_0", "feature_1", "feature_2", "feature_3"] 
  max_features_to_show: 6
  n_bins: 25
  save_to_dir: null 