# GLOBAL
global_settings:
  random_seed: 42

# DATA GENERATOR MODULE
dataset_settings:
  n_samples: 1000000
  n_initial_features: 20

feature_generation:
  feature_parameters:
    feature_0: {mean: 10.0, std: 2.0}
    feature_1: {mean: -5.0, std: 1.5}
    feature_2: {mean: 0.0, std: 2.5}
    feature_3: {mean: 3.0, std: 1.0}
    feature_4: {mean: -2.0, std: 0.8}
    feature_5: {mean: 15.0, std: 3.0}
    feature_6: {mean: -8.0, std: 2.2}
    feature_7: {mean: 5.0, std: 1.8}
    feature_8: {mean: -1.0, std: 0.9}
    feature_9: {mean: 12.0, std: 2.8}
    feature_10: {mean: -6.0, std: 1.3}
    feature_11: {mean: 8.0, std: 2.1}
    feature_12: {mean: -3.0, std: 1.1}
    feature_13: {mean: 20.0, std: 4.0}
    feature_14: {mean: -10.0, std: 2.5}
    feature_15: {mean: 7.0, std: 1.6}
    feature_16: {mean: -4.0, std: 1.4}
    feature_17: {mean: 25.0, std: 5.0}
    feature_18: {mean: -12.0, std: 3.2}
    feature_19: {mean: 18.0, std: 3.8}
  feature_types:
    feature_0: "continuous"
    feature_1: "continuous"
    feature_2: "continuous"
    feature_3: "continuous"
    feature_4: "continuous"
    feature_5: "continuous"
    feature_6: "continuous"
    feature_7: "continuous"
    feature_8: "continuous"
    feature_9: "continuous"
    feature_10: "continuous"
    feature_11: "continuous"
    feature_12: "continuous"
    feature_13: "continuous"
    feature_14: "continuous"
    feature_15: "continuous"
    feature_16: "continuous"
    feature_17: "continuous"
    feature_18: "continuous"
    feature_19: "continuous"


create_target:
  features_to_use: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8", "feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18", "feature_19"]
  weights: [3.5, -2.8, 0.1, 5.2, -4.1, 1.7, -0.05, 2.9, -1.2, 0.8, -3.3, 0.4, 4.6, -0.9, 2.1, -5.0, 0.3, 3.8, -1.6, 0.0]
  noise_level: 0
  function_type: "linear"

visualisation:
  features: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8", "feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18", "feature_19"]
  max_features_to_show: 20
  n_bins: 25
  # --- FIX 1: Corrected syntax and path format ---
  save_to_dir: "reports/figures/"

  # TRAINING
training_settings:
  output_data_dir: "data/"
  target_column: "target"
  model_output_dir: "models/"
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
  hyperparameters:
    hidden_size: 64
    output_size: 1
    learning_rate: 0.001
    epochs: 50
    batch_size: 32