create_feature_based_signal_noise_classification:
  feature_types:
    feature_0: discrete
    feature_1: discrete
    feature_2: discrete
    feature_3: discrete
    feature_4: discrete
    feature_5: discrete
    feature_6: discrete
    feature_7: discrete
    feature_8: discrete
    feature_9: discrete
  noise_features:
    feature_0:
      mean: 1.0
      std: 1.8
    feature_1:
      mean: 0.5
      std: 2.2
    feature_2:
      mean: 3.0
      std: 3.0
    feature_3:
      mean: -1.5
      std: 2.8
    feature_4:
      mean: 1.2
      std: 2.4
    feature_5:
      mean: 1.2
      std: 2.2
    feature_6:
      mean: 0.0
      std: 2.5
    feature_7:
      mean: -3.0
      std: 2.1
    feature_8:
      mean: 1.0
      std: 2.9
    feature_9:
      mean: 2.0
      std: 3.1
  signal_features:
    feature_0:
      mean: 2.0
      std: 2.2
    feature_1:
      mean: -1.5
      std: 2.8
    feature_2:
      mean: 4.0
      std: 2.0
    feature_3:
      mean: 1.5
      std: 3.2
    feature_4:
      mean: 0.0
      std: 1.5
    feature_5:
      mean: 3.0
      std: 2.9
    feature_6:
      mean: 2.5
      std: 3.0
    feature_7:
      mean: -2.0
      std: 1.9
    feature_8:
      mean: 5.25
      std: 2.5
    feature_9:
      mean: 1.0
      std: 3.5
dataset_settings:
  continuous_decimal_places: 4
  n_initial_features: 10
  n_samples: 1000000
global_settings:
  random_seed: 4
perturbation_settings:
- class_label: 0
  feature: feature_4
  scale_factor: 1.5
visualisation:
  max_features_to_show: 10
  n_bins: 25
  save_to_dir: reports/figures/
