create_feature_based_signal_noise_classification:
  feature_types:
    feature_0: discrete
    feature_1: discrete
    feature_2: discrete
    feature_3: discrete
    feature_4: discrete
    feature_5: discrete
    feature_6: discrete
    feature_7: discrete
    feature_8: discrete
    feature_9: discrete
  noise_features:
    feature_0:
      mean: 2.0
      std: 2.8
    feature_1:
      mean: 2.5
      std: 2.5
    feature_2:
      mean: 2.0
      std: 3.0
    feature_3:
      mean: 3.0
      std: 2.0
    feature_4:
      mean: 1.0
      std: 1.8
    feature_5:
      mean: 2.0
      std: 2.8
    feature_6:
      mean: 2.5
      std: 2.5
    feature_7:
      mean: 2.0
      std: 3.0
    feature_8:
      mean: 3.0
      std: 2.0
    feature_9:
      mean: 1.0
      std: 1.8
  signal_features:
    feature_0:
      mean: 2.7
      std: 2.0
    feature_1:
      mean: 1.4
      std: 3.5
    feature_2:
      mean: 3.1
      std: 1.5
    feature_3:
      mean: -0.5
      std: 2.5
    feature_4:
      mean: 2.1
      std: 1.0
    feature_5:
      mean: 2.7
      std: 2.0
    feature_6:
      mean: 1.4
      std: 3.5
    feature_7:
      mean: 3.1
      std: 1.5
    feature_8:
      mean: -0.5
      std: 2.5
    feature_9:
      mean: 2.1
      std: 1.0
dataset_settings:
  continuous_decimal_places: 4
  n_initial_features: 10
  n_samples: 1000000
global_settings:
  random_seed: 1
visualisation:
  max_features_to_show: 10
  n_bins: 25
  save_to_dir: reports/figures/
