dataset_settings:
  n_samples: 1000
  n_initial_features: 2
  continuous_decimal_places: 4

global_settings:
  random_seed: 99

create_feature_based_signal_noise_classification:
  feature_types:
    feature_0: continuous
    feature_1: continuous
  signal_features:
    feature_0: {mean: 2.0, std: 1.0}
    feature_1: {mean: 2.0, std: 1.0}
  noise_features:
    feature_0: {mean: 0.0, std: 1.0}
    feature_1: {mean: 0.0, std: 1.0}

output_settings:
  data_dir: data/project_health_smoke
