# configs/training/model-001.yml
training_settings:
  output_data_dir: "data/"
  target_column: "target"
  model_output_dir: "models/"
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
  hyperparameters:
    hidden_size: 64
    output_size: 1
    learning_rate: 0.001
    epochs: 50
    batch_size: 32