perturbation_settings:
- type: correlated
  class_label: 0
  features:
  - feature_0
  - feature_1
  - feature_2
  - feature_4
  correlation_matrix:
  - - 1.0
    - 0.7
    - 0.5
    - 0.4
  - - 0.7
    - 1.0
    - 0.6
    - 0.3
  - - 0.5
    - 0.6
    - 1.0
    - 0.2
  - - 0.4
    - 0.3
    - 0.2
    - 1.0
  sigma_shift: 0.25
