training_settings:
  output_data_dir: data/
  target_column: target
  model_output_dir: models/
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
  hyperparameters:
    hidden_size: 128
    learning_rate: 0.000100429172907137
    batch_size: 16
    epochs: 10
    output_size: 1
