training_settings:
  output_data_dir: data/
  target_column: target
  model_output_dir: models/
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
  model_name: mlp_001
  scheduler_settings:
    mode: min
    factor: 0.1
    patience: 5
  early_stopping_settings:
    patience: 10
  hyperparameters:
    hidden_size: 48
    output_size: 1
    learning_rate: 0.001137254483400315
    epochs: 300
    batch_size: 32
    weight_decay: 0.0024991804049363754
  optimal_trial_number: 8
