training_settings:
  output_data_dir: data/
  target_column: target
  model_output_dir: models/
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
  hyperparameters:
    output_size: 1
    learning_rate: 0.00018519827219391834
    epochs: 45
    batch_size: 32
  model_name: LogisticRegression
