source_data_config: configs/data_generation/n10000_f_init5_cont0_disc5_sep6p6_seed42_config.yml
source_training_config: configs/training/generated/n10000_f_init5_cont0_disc5_sep6p6_seed42_mlp_optimal.yml
training_settings:
  hyperparameters:
    batch_size: 64
    epochs: 10
    hidden_size: 160
    learning_rate: 3.81047019751266e-05
    output_size: 1
  model_name: MLP
  model_output_dir: models/
  output_data_dir: data/
  target_column: target
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
