source_data_config: configs\data_generation\n1000_f_init5_cont0_disc5_sep6p6_config.yml
source_training_config: configs\training\model-001.yml
training_settings:
  hyperparameters:
    batch_size: 32
    epochs: 50
    hidden_size: 64
    learning_rate: 0.001
    output_size: 1
  model_output_dir: models/
  output_data_dir: data/
  target_column: target
  test_set_ratio: 0.2
  validation_set_ratio: 0.2
