tuning_jobs:
  logistic-regression:
    description: "Tune Logistic Regression"
    num_workers: 4
    n_trials: 50
    sample_fraction: 1.0
    tuning_config: "configs/tuning/logistic-regression.yml"
    base_training_config: "configs/training/templates/logistic-regression.yml"

  mlp:
    description: "Tune MLP"
    num_workers: 4
    n_trials: 50
    sample_fraction: 1.0
    tuning_config: "configs/tuning/mlp.yml"
    base_training_config: "configs/training/templates/mlp.yml"