# GLOBAL
global_settings:
  random_seed: 42

# Dataset settings
dataset_settings:
  n_samples: 100000
  n_initial_features: 5

# Feature-based signal vs noise classification
create_feature_based_signal_noise_classification:
  signal_features:
    feature_0: {mean: 20.0, std: 1.5}
    feature_1: {mean: -15.0, std: 1.5}
    feature_2: {mean: 10.0, std: 1.5}
    feature_3: {mean: -5.0, std: 1.5}
    feature_4: {mean: 25.0, std: 1.5}
  noise_features:
    feature_0: {mean: -20.0, std: 1.5}
    feature_1: {mean: 15.0, std: 1.5}
    feature_2: {mean: -10.0, std: 1.5}
    feature_3: {mean: 5.0, std: 1.5}
    feature_4: {mean: -25.0, std: 1.5}
  feature_types:
    feature_0: "discrete"
    feature_1: "discrete"
    feature_2: "discrete"
    feature_3: "discrete"
    feature_4: "discrete"

# Visualisation settings
visualisation:
  max_features_to_show: 5
  n_bins: 25
  save_to_dir: "reports/figures/"
