# GLOBAL
global_settings:
  random_seed: 42

# DATA GENERATOR MODULE
dataset_settings:
  n_samples: 1000000
  n_initial_features: 20

feature_generation:
  feature_parameters:
    feature_0: {mean: 10.0, std: 2.0}
    feature_1: {mean: -5.0, std: 1.5}
    feature_2: {mean: 0.0, std: 2.5}
    feature_3: {mean: 3.0, std: 1.0}
    feature_4: {mean: -2.0, std: 0.8}
    feature_5: {mean: 15.0, std: 3.0}
    feature_6: {mean: -8.0, std: 2.2}
    feature_7: {mean: 5.0, std: 1.8}
    feature_8: {mean: -1.0, std: 0.9}
    feature_9: {mean: 12.0, std: 2.8}
    feature_10: {mean: -6.0, std: 1.3}
    feature_11: {mean: 8.0, std: 2.1}
    feature_12: {mean: -3.0, std: 1.1}
    feature_13: {mean: 20.0, std: 4.0}
    feature_14: {mean: -10.0, std: 2.5}
    feature_15: {mean: 7.0, std: 1.6}
    feature_16: {mean: -4.0, std: 1.4}
    feature_17: {mean: 25.0, std: 5.0}
    feature_18: {mean: -12.0, std: 3.2}
    feature_19: {mean: 18.0, std: 3.8}
  feature_types:
    feature_0: "discrete"
    feature_1: "discrete"
    feature_2: "discrete"
    feature_3: "discrete"
    feature_4: "discrete"
    feature_5: "discrete"
    feature_6: "discrete"
    feature_7: "discrete"
    feature_8: "discrete"
    feature_9: "discrete"
    feature_10: "discrete"
    feature_11: "discrete"
    feature_12: "discrete"
    feature_13: "discrete"
    feature_14: "discrete"
    feature_15: "discrete"
    feature_16: "discrete"
    feature_17: "discrete"
    feature_18: "discrete"
    feature_19: "discrete"


create_target:
  features_to_use: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8", "feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18", "feature_19"]
  weights: [3.5, -2.8, 0.1, 5.2, -4.1, 1.7, -0.05, 2.9, -1.2, 0.8, -3.3, 0.4, 4.6, -0.9, 2.1, -5.0, 0.3, 3.8, -1.6, 0.0]
  noise_level: 0
  function_type: "linear"

visualisation:
  features: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6", "feature_7", "feature_8", "feature_9", "feature_10", "feature_11", "feature_12", "feature_13", "feature_14", "feature_15", "feature_16", "feature_17", "feature_18", "feature_19"]
  max_features_to_show: 20
  n_bins: 25

  save_to_dir: "reports/figures/"

