# GLOBAL
global_settings:
  random_seed: 42

# DATA GENERATOR MODULE
dataset_settings:
  n_samples: 1000
  n_initial_features: 5

feature_generation:
  feature_parameters:
    feature_0: {mean: 10.0, std: 2.0}
    feature_1: {mean: -5.0, std: 1.5}
    feature_2: {mean: 0.0, std: 2.5}
    feature_3: {mean: 3.0, std: 1.0}
    feature_4: {mean: -2.0, std: 0.8}


  feature_types:
    feature_0: "discrete"
    feature_1: "discrete"
    feature_2: "discrete"
    feature_3: "discrete"
    feature_4: "discrete"



create_gaussian_signal_noise_target:
  signal_distribution_params:
    mean: 2.0      # Signal centered at 2.0
    std: 0.8       # Signal standard deviation
  noise_distribution_params:
    mean: -1.0     # Noise centered at -1.0  
    std: 1.2       # Noise standard deviation
  signal_ratio: 0.6  # 60% signal, 40% noise
  target_feature: "signal_strength"

visualisation:
  features: ["feature_0", "feature_1", "feature_2", "feature_3", "feature_4"]
  max_features_to_show: 6
  n_bins: 25

  save_to_dir: "reports/figures/"

