perturbation_settings:
- type: correlated
  class_label: 0
  features:
  - feature_0
  - feature_2
  - feature_4
  correlation_matrix:
  - - 1.0
    - 0.7
    - 0.5
  - - 0.7
    - 1.0
    - 0.6
  - - 0.5
    - 0.6
    - 1.0
  scale_factor: 1.5
  description: ''
