perturbation_settings:
- type: "correlated"
  class_label: 1  # Apply to signal class
  features: ["feature_0", "feature_4"]
  correlation_matrix:
    - [1.0, 0.8]
    - [0.8, 1.0]
  scale_factor: 1.5
  description: "Sensor drift correlation"